export const SEARCH_TERM_CHANGED = 'SEARCH_TERM_CHANGED';
export const SEARCH_TERM_RESET = 'SEARCH_TERM_RESET';
export const USER_NAMES_FOUND = 'USER_NAMES_FOUND';
export const ONE_USER_NAME_FOUND = 'ONE_USER_NAME_FOUND';
export const ON_CLICK_SUGGESTION ='ON_CLICK_SUGGESTION';
export const ON_CLICK_SUGGESTION_SUCCESSS ='ON_CLICK_SUGGESTION_SUCCESS';
export const SCROLL_COUNT_CHANGED = 'SCROLL_COUNT_CHANGED';
export const REPO_SCROLL_COUNT_CHANGED = 'REPO_SCROLL_COUNT_CHANGED';
export const NEXT_PAGE = 'NEXT_PAGE';
export const NEXT_REPO_PAGE = 'NEXT_REPO_PAGE';

